use std::path::Path;
use std::time::Duration;

use anyhow::{Context, Result, bail};
use claudectl::config;
use claudectl::exec::{SelfIdentity, sha256_file};
use claudectl::profile;

/// Write an executable script that runs `claude` on one saved profile through
/// `claudectl exec`, pinned to the profile's accountUuid, the executable's
/// SHA-256, and this claudectl binary's path and SHA-256.
pub fn run(alias: &str, claude: &Path, out: &Path, min_valid: Duration) -> Result<()> {
    let paths = config::default_paths()?;
    let alias = profile::validate_alias(alias)?;
    let saved = profile::get_profile_from(&paths, alias)?;
    let account = saved
        .meta
        .account_uuid()
        .with_context(|| {
            format!("'{alias}' has no saved accountUuid; run `claudectl login {alias}` again")
        })?
        .to_string();
    if profile::get_active_from(&paths)?.as_deref() == Some(alias) {
        bail!("'{alias}' is the active profile; a launcher cannot pin it");
    }
    let claude = claude
        .canonicalize()
        .with_context(|| format!("cannot resolve {}", claude.display()))?;
    let claude_sha = sha256_file(&claude).map_err(|e| anyhow::anyhow!("{e}"))?;
    let me = SelfIdentity::current().map_err(|e| anyhow::anyhow!("{e}"))?;

    let script = render(alias, &account, &claude, &claude_sha, &me, min_valid)?;
    let tmp = out.with_extension("tmp");
    std::fs::write(&tmp, script).with_context(|| format!("failed to write {}", tmp.display()))?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&tmp, std::fs::Permissions::from_mode(0o700))?;
    }
    std::fs::rename(&tmp, out).with_context(|| format!("failed to write {}", out.display()))?;
    println!("{}", out.display());
    Ok(())
}

fn quoted(value: &str) -> Result<String> {
    if value.contains('\'') || value.contains('\n') {
        bail!("value {value:?} cannot be pinned in a launcher");
    }
    Ok(format!("'{value}'"))
}

fn render(
    alias: &str,
    account: &str,
    claude: &Path,
    claude_sha: &str,
    me: &SelfIdentity,
    min_valid: Duration,
) -> Result<String> {
    let claudectl = quoted(&me.path.to_string_lossy())?;
    Ok(format!(
        r#"#!/bin/sh
# Generated by claudectl {version} launcher. Runs one pinned executable on saved
# profile {alias} only. Any change to the profile, the executable or claudectl
# makes it refuse to run.
set -eu
CLAUDECTL={claudectl}
if command -v shasum >/dev/null 2>&1; then sum() {{ shasum -a 256 "$1"; }}; else sum() {{ sha256sum "$1"; }}; fi
if [ "$(sum "$CLAUDECTL" | cut -d' ' -f1)" != {me_sha} ]; then
  echo "claudectl launcher: $CLAUDECTL changed since this launcher was written; refusing" >&2
  exit 4
fi
exec "$CLAUDECTL" exec --profile {alias_q} --expect-account {account} --expect-sha256 {claude_sha} \
  --min-valid {min_valid}s ${{CLAUDECTL_RECEIPT:+--receipt "$CLAUDECTL_RECEIPT"}} -- {claude} "$@"
"#,
        version = me.version,
        alias = alias,
        alias_q = quoted(alias)?,
        account = quoted(account)?,
        claude_sha = quoted(claude_sha)?,
        me_sha = quoted(&me.sha256)?,
        min_valid = min_valid.as_secs(),
        claude = quoted(&claude.to_string_lossy())?,
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn launcher_pins_profile_account_executable_and_claudectl() {
        let me = SelfIdentity {
            path: "/opt/claudectl".into(),
            sha256: "a".repeat(64),
            version: "0.1.5".into(),
        };
        let script = render(
            "work",
            "uuid-work",
            Path::new("/opt/claude"),
            &"b".repeat(64),
            &me,
            Duration::from_secs(1800),
        )
        .unwrap();
        assert!(script.contains("--profile 'work' --expect-account 'uuid-work'"));
        assert!(script.contains(&format!("--expect-sha256 '{}'", "b".repeat(64))));
        assert!(script.contains(&format!("!= '{}'", "a".repeat(64))));
        assert!(script.contains("--min-valid 1800s"));
        assert!(script.contains("-- '/opt/claude' \"$@\""));
    }

    #[test]
    fn launcher_refuses_values_it_cannot_quote() {
        let me = SelfIdentity {
            path: "/opt/it's".into(),
            sha256: "a".repeat(64),
            version: "0.1.5".into(),
        };
        assert!(
            render(
                "w",
                "u",
                Path::new("/opt/claude"),
                "b",
                &me,
                Duration::from_secs(1)
            )
            .is_err()
        );
    }
}
