//! `claudectl shim`: a `claude` launcher, first on PATH, that runs Claude through
//! `claudectl server run` (SAW-12668). The launcher passes the real Claude by path, so
//! `server run` never finds the launcher itself on PATH. It holds no credential.
use anyhow::{Context, Result, bail};
use serde::{Deserialize, Serialize};
use std::ffi::OsStr;
use std::io::Read;
use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};

/// The line that marks a file as a launcher this module wrote.
pub const MARKER: &str = "# claudectl-shim v1";
/// First arguments that run the real Claude without a server token.
const PASS_THROUGH: &str = "-v|--version|-h|--help|update|doctor|install";

/// What a launcher runs: which server account, which real Claude, which claudectl.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Spec {
    pub alias: String,
    pub real: PathBuf,
    pub claudectl: PathBuf,
}

#[derive(clap::Subcommand)]
pub enum Command {
    /// Make plain `claude` run through `claudectl server run <account>`
    Install {
        /// Server account alias every `claude` run uses (default: `default_account()`)
        #[arg(long)]
        account: Option<String>,
        /// The real Claude executable (default: the first non-shim `claude` on PATH)
        #[arg(long)]
        claude: Option<PathBuf>,
        /// Directory for the launcher (default: ~/.local/claudectl/bin)
        #[arg(long)]
        dir: Option<PathBuf>,
    },
    /// Remove the launcher (only a file this command wrote)
    Uninstall {
        #[arg(long)]
        dir: Option<PathBuf>,
    },
    /// Show the launcher, its account and real Claude, and whether PATH finds it first
    Status {
        #[arg(long)]
        dir: Option<PathBuf>,
    },
}

/// The server account a launcher uses when install names none. This is the hook for the
/// capacity picker (SAW-12555): it can choose the server account with room here. It never
/// picks a usage-billed account.
pub fn default_account() -> &'static str {
    "amir@sawmills.ai"
}

/// True when `path` (followed through symlinks) is a launcher this module wrote.
pub fn is_shim(path: &Path) -> bool {
    let Ok(file) = std::fs::File::open(path) else {
        return false;
    };
    let mut head = Vec::with_capacity(512);
    if file.take(512).read_to_end(&mut head).is_err() {
        return false;
    }
    String::from_utf8_lossy(&head)
        .lines()
        .any(|line| line == MARKER)
}

/// A regular file (through symlinks) that this process may execute (access(2) X_OK, the
/// effective check, not only some class's mode bit).
fn is_executable(path: &Path) -> bool {
    use std::os::unix::ffi::OsStrExt;
    path.metadata().is_ok_and(|m| m.is_file())
        && std::ffi::CString::new(path.as_os_str().as_bytes())
            .is_ok_and(|c| unsafe { libc::access(c.as_ptr(), libc::X_OK) } == 0)
}

fn quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', r"'\''"))
}
fn text(path: &Path) -> Result<&str> {
    path.to_str()
        .with_context(|| format!("{} is not valid UTF-8", path.display()))
}

/// The launcher script for `spec`. Every value is single-quoted for sh.
pub fn render(spec: &Spec) -> Result<String> {
    let real = quote(text(&spec.real)?);
    let claudectl = quote(text(&spec.claudectl)?);
    let alias = quote(&spec.alias);
    let recorded = serde_json::to_string(spec)?;
    Ok(format!(
        "#!/bin/sh\n\
         {MARKER}\n\
         # Generated by `claudectl shim install`; run it again to change this file.\n\
         # spec {recorded}\n\
         real={real}\n\
         if [ \"${{CLAUDECTL_SHIM:-}}\" = off ]; then exec \"$real\" \"$@\"; fi\n\
         case \"${{1:-}}\" in {PASS_THROUGH}) exec \"$real\" \"$@\" ;; esac\n\
         exec {claudectl} server run {alias} --claude \"$real\" -- \"$@\"\n"
    ))
}

/// The recorded spec of a launcher, if `path` is one.
fn read_spec(path: &Path) -> Option<Spec> {
    let script = std::fs::read_to_string(path).ok()?;
    let line = script.lines().find_map(|l| l.strip_prefix("# spec "))?;
    serde_json::from_str(line).ok()
}

/// Refuse a real Claude that is missing, relative, or any launcher (no recursion).
fn check_real(real: &Path, target: &Path) -> Result<()> {
    if !real.is_absolute() {
        bail!("the real Claude path must be absolute: {}", real.display());
    }
    if !is_executable(real) {
        bail!(
            "the real Claude is not an executable file: {}",
            real.display()
        );
    }
    let same = |a: &Path, b: &Path| matches!((a.canonicalize(), b.canonicalize()), (Ok(a), Ok(b)) if a == b);
    if is_shim(real) || same(real, target) {
        bail!(
            "{} is a claudectl shim, not Claude; pass the real Claude with --claude",
            real.display()
        );
    }
    Ok(())
}

/// Write `<dir>/claude` for `spec`. Replaces an earlier launcher; never a foreign file.
pub fn install(spec: &Spec, dir: &Path) -> Result<PathBuf> {
    crate::profile::validate_alias(&spec.alias)?;
    if dir.to_string_lossy().contains(':') {
        bail!("PATH cannot name a directory with ':'; pick another --dir");
    }
    if spec.alias.starts_with('-') {
        bail!(
            "an alias that starts with '-' reads as an option in `server run`; rename the server account"
        );
    }
    let target = dir.join("claude");
    check_real(&spec.real, &target)?;
    if !spec.claudectl.is_absolute() || !is_executable(&spec.claudectl) {
        bail!("claudectl not found at {}", spec.claudectl.display());
    }
    if target.symlink_metadata().is_ok() && !is_shim(&target) {
        bail!(
            "{} exists and is not a claudectl shim; move it first",
            target.display()
        );
    }
    let script = render(spec)?;
    std::fs::create_dir_all(dir)?;
    // Write a new sibling, then rename: a running `claude` never sees half a file. The
    // sibling is created exclusively (O_EXCL), so a planted file or symlink is refused,
    // never written through.
    let partial = dir.join(format!(
        ".claude.claudectl-shim.{}.{}.tmp",
        std::process::id(),
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map_or(0, |d| d.as_nanos())
    ));
    let written = (|| -> Result<()> {
        use std::io::Write;
        use std::os::unix::fs::OpenOptionsExt;
        let mut file = std::fs::OpenOptions::new()
            .write(true)
            .create_new(true)
            .mode(0o755)
            .open(&partial)?;
        file.write_all(script.as_bytes())?;
        // On the open handle (fchmod), not by path: the umask may have cleared bits.
        file.set_permissions(std::fs::Permissions::from_mode(0o755))?;
        file.sync_all()?;
        std::fs::rename(&partial, &target)?;
        Ok(())
    })();
    if written.is_err() {
        let _ = std::fs::remove_file(&partial);
    }
    written?;
    Ok(target)
}

/// Remove `<dir>/claude` when it is a launcher. False when there is none.
pub fn uninstall(dir: &Path) -> Result<bool> {
    let target = dir.join("claude");
    if target.symlink_metadata().is_err() {
        return Ok(false);
    }
    if !is_shim(&target) {
        bail!(
            "{} is not a claudectl shim; it was left in place",
            target.display()
        );
    }
    std::fs::remove_file(&target)?;
    Ok(true)
}

/// The real Claude: `explicit` as given, or the first `claude` on `path` that is a file
/// and not a launcher. The path is kept as found, so an installer symlink keeps following
/// updates.
pub fn find_real(explicit: Option<&Path>, path: &OsStr) -> Result<PathBuf> {
    find_real_from(explicit, path, &std::env::current_dir()?)
}

/// `path` joined to `base` when relative. Lexical only: a symlink stays a symlink.
pub fn absolute(path: &Path, base: &Path) -> PathBuf {
    if path.is_absolute() {
        path.to_path_buf()
    } else {
        base.join(path)
    }
}

/// `find_real`, with relative PATH entries and `explicit` read against `base`.
pub fn find_real_from(explicit: Option<&Path>, path: &OsStr, base: &Path) -> Result<PathBuf> {
    if let Some(real) = explicit {
        let real = &absolute(real, base);
        if !is_executable(real) || is_shim(real) {
            bail!("{} is not a Claude executable", real.display());
        }
        return Ok(real.to_path_buf());
    }
    std::env::split_paths(path)
        .map(|dir| absolute(&dir, base).join("claude"))
        .find(|candidate| is_executable(candidate) && !is_shim(candidate))
        .context("no Claude executable on PATH apart from a claudectl shim; pass --claude")
}

/// The first executable `name` on `path`.
fn on_path(name: &str, path: &OsStr) -> Option<PathBuf> {
    std::env::split_paths(path)
        .map(|dir| dir.join(name))
        .find(|candidate| is_executable(candidate))
}

#[derive(Debug)]
pub struct Status {
    pub installed: bool,
    pub alias: Option<String>,
    pub real: Option<PathBuf>,
    pub real_ok: bool,
    pub claudectl: Option<PathBuf>,
    /// The recorded claudectl is still an executable file.
    pub claudectl_ok: bool,
    /// `claude` on this PATH resolves to the launcher.
    pub first_on_path: bool,
}

pub fn status(dir: &Path, path: &OsStr) -> Result<Status> {
    let target = dir.join("claude");
    let installed = is_shim(&target);
    let spec = installed.then(|| read_spec(&target)).flatten();
    let real_ok = spec
        .as_ref()
        .is_some_and(|s| is_executable(&s.real) && !is_shim(&s.real));
    let claudectl_ok = spec.as_ref().is_some_and(|s| is_executable(&s.claudectl));
    let first_on_path = installed
        && on_path("claude", path).is_some_and(|found| {
            matches!((found.canonicalize(), target.canonicalize()), (Ok(a), Ok(b)) if a == b)
        });
    Ok(Status {
        installed,
        alias: spec.as_ref().map(|s| s.alias.clone()),
        real: spec.as_ref().map(|s| s.real.clone()),
        real_ok,
        claudectl: spec.map(|s| s.claudectl),
        claudectl_ok,
        first_on_path,
    })
}

/// Refuse a `server run --claude` program that is a launcher: it would run itself.
pub fn refuse_shim_program(claude: &Path) -> Result<()> {
    if let Ok(program) = super::session::program(claude)
        && is_shim(&program)
    {
        bail!(
            "{} is a claudectl shim, not Claude; pass the real Claude with --claude (see `claudectl shim status`)",
            program.display()
        );
    }
    Ok(())
}

/// The claudectl path a launcher records: the PATH entry for `me` when there is one (a
/// package manager's stable link survives upgrades), else `me`. Always absolute: a
/// relative PATH entry is read against `base`.
pub fn claudectl_path_from(path: &OsStr, base: &Path, me: &Path) -> PathBuf {
    let me = me.canonicalize().unwrap_or_else(|_| me.to_path_buf());
    std::env::split_paths(path)
        .map(|dir| absolute(&dir, base).join("claudectl"))
        .find(|candidate| is_executable(candidate))
        .filter(|found| found.canonicalize().is_ok_and(|c| c == me))
        .unwrap_or(me)
}

/// The shell line that puts `dir` first on PATH. A directory with characters the shell
/// would expand is single-quoted, so pasting the line runs nothing.
pub fn path_line(dir: &Path) -> String {
    let dir = dir.to_string_lossy();
    if dir
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || "/._-+@".contains(c))
    {
        format!("export PATH=\"{dir}:$PATH\"")
    } else {
        format!("export PATH={}:\"$PATH\"", quote(&dir))
    }
}

fn default_dir(paths: &crate::config::Paths) -> PathBuf {
    paths.home.join(".local").join("claudectl").join("bin")
}

pub fn dispatch(command: Command) -> Result<()> {
    let paths = &crate::config::default_paths()?;
    let path = std::env::var_os("PATH").unwrap_or_default();
    let cwd = std::env::current_dir()?;
    // A relative --dir would point elsewhere from every later shell: make it absolute.
    let resolve =
        |dir: Option<PathBuf>| dir.map_or_else(|| default_dir(paths), |d| absolute(&d, &cwd));
    match command {
        Command::Install {
            account,
            claude,
            dir,
        } => {
            let dir = resolve(dir);
            let account = account.unwrap_or_else(|| default_account().into());
            // Only a server account: the launcher never falls back to a local or billed login.
            super::Client::load(paths)?.account(&account)?;
            let spec = Spec {
                alias: account,
                real: find_real(claude.as_deref(), &path)?,
                claudectl: claudectl_path_from(&path, &cwd, &std::env::current_exe()?),
            };
            let target = install(&spec, &dir)?;
            println!("Installed {}", target.display());
            println!("  account   {}", spec.alias);
            println!("  claude    {}", spec.real.display());
            println!("  claudectl {}", spec.claudectl.display());
            if status(&dir, &path)?.first_on_path {
                println!("`claude` on this PATH already runs the shim.");
            } else {
                println!("Put this line in your shell profile, then open a new terminal:");
                println!("  {}", path_line(&dir));
            }
            println!("Escape hatch: CLAUDECTL_SHIM=off claude ...");
            Ok(())
        }
        Command::Uninstall { dir } => {
            let dir = resolve(dir);
            if uninstall(&dir)? {
                println!("Removed {}", dir.join("claude").display());
            } else {
                println!("No shim at {}", dir.join("claude").display());
            }
            Ok(())
        }
        Command::Status { dir } => {
            let dir = resolve(dir);
            let s = status(&dir, &path)?;
            if !s.installed {
                println!("No shim at {}", dir.join("claude").display());
                std::process::exit(1);
            }
            println!("shim      {}", dir.join("claude").display());
            println!("account   {}", s.alias.as_deref().unwrap_or("unknown"));
            match &s.real {
                Some(real) if s.real_ok => println!("claude    {}", real.display()),
                Some(real) => println!("claude    {} (missing: run install again)", real.display()),
                None => println!("claude    unknown"),
            }
            match &s.claudectl {
                Some(c) if s.claudectl_ok => println!("claudectl {}", c.display()),
                Some(c) => println!("claudectl {} (missing: run install again)", c.display()),
                None => println!("claudectl unknown"),
            }
            println!(
                "PATH      {}",
                if s.first_on_path {
                    "`claude` runs the shim"
                } else {
                    "`claude` does not run the shim; put the shim directory first on PATH"
                }
            );
            if !(s.real_ok && s.claudectl_ok && s.first_on_path) {
                std::process::exit(1);
            }
            Ok(())
        }
    }
}
